import { createHash } from 'node:crypto';
import { readFile, readdir } from 'node:fs/promises';
import { fileCache } from './cache.mjs';
import { generateReader, loadPlaces } from './reader.mjs';
import { judgeTranslation } from './judge.mjs';
import { UnavailableError } from './provider.mjs';

export const contentName = (id, level) => `${id.replace(':', '-')}-${level}.json`;
export const validId = id => /^(jp:\d{5}|region:Q\d+)$/.test(id);
export const levels = ['beginner', 'intermediate', 'advanced'];

export async function createService(root, provider) {
  const places = await loadPlaces(root);
  const byId = new Map(places.map(p => [p.id, p]));
  const sentences = new Map();
  const pending = new Map();
  const cards = fileCache(`${root}/.data-cache/readers`);
  const judgments = fileCache(`${root}/.data-cache/judgments`);
  const remember = card => { for (const s of card.sentences) sentences.set(s.id, s); return card; };
  const directory = `${root}/public/data/content`;
  try {
    for (const name of await readdir(directory)) {
      if (name.endsWith('.json') && name !== 'manifest.json') remember(JSON.parse(await readFile(`${directory}/${name}`, 'utf8')));
    }
  } catch (e) { if (e.code !== 'ENOENT') throw e; }
  return {
    async content(id, level) {
      if (!validId(id) || !byId.has(id) || !levels.includes(level)) return null;
      try { return remember(JSON.parse(await readFile(`${directory}/${contentName(id, level)}`, 'utf8'))); }
      catch (e) { if (e.code !== 'ENOENT') throw e; }
      const facts = JSON.parse(await readFile(`${root}/data/facts/${id.replace(':', '-')}.json`, 'utf8')).facts;
      const key = createHash('sha256').update(JSON.stringify(['reader-v1', id, level, facts, provider.model])).digest('hex');
      const cached = await cards.get(key);
      if (cached) return remember(cached);
      if (!provider.model) throw new UnavailableError('The reader service needs a server-side model connection.');
      if (!pending.has(key)) {
        if (pending.size >= 2) throw new UnavailableError('The reader service is busy. Try again shortly.');
        const request = generateReader({ root, place: byId.get(id), places, facts, level, provider, autoGenerated: true })
          .then(async card => { await cards.set(key, card); return remember(card); })
          .finally(() => pending.delete(key));
        pending.set(key, request);
      }
      return pending.get(key);
    },
    async judge(id, answer) {
      const sentence = sentences.get(id);
      if (!sentence) return null;
      return judgeTranslation(sentence, answer, provider, judgments);
    },
  };
}
