import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { configuredProvider } from '../server/configured-provider.mjs';
import { generateReader, loadPlaces } from '../server/reader.mjs';
import { contentName, levels } from '../server/service.mjs';

try { process.loadEnvFile('.env'); } catch (e) { if (e.code !== 'ENOENT') throw e; }
const root = fileURLToPath(new URL('..', import.meta.url)).replace(/\/$/, '');
const provider = configuredProvider();
const places = await loadPlaces(root);
const targets = places.filter(p => ['region', 'prefecture', 'major-city'].includes(p.kind));
const requested = process.argv[2];
const selectedLevel = process.argv[3];
if (selectedLevel && !levels.includes(selectedLevel)) throw new Error('Unknown sentence level.');
if (requested && !targets.some(p => p.id === requested)) throw new Error('Requested build-tier place does not exist.');
const directory = `${root}/public/data/content`;
await mkdir(directory, { recursive: true });
const generated = [];
for (const place of targets.filter(p => !requested || p.id === requested)) {
  const facts = JSON.parse(await readFile(`${root}/data/facts/${place.id.replace(':', '-')}.json`, 'utf8')).facts;
  for (const level of levels.filter(level => !selectedLevel || level === selectedLevel)) {
    const name = contentName(place.id, level);
    const card = await generateReader({ root, place, places, facts, level, provider, autoGenerated: false });
    await writeFile(`${directory}/${name}`, JSON.stringify(card));
    generated.push({ place_id: place.id, level, url: `/data/content/${name}` });
    console.log(`Validated ${place.name_kanji} · ${level}`);
  }
}
// A partial proof run must not masquerade as full build-tier coverage.
await writeFile(`${root}/reports/content-build.json`, JSON.stringify({ status: requested ? 'partial' : 'generated', expected_cards: targets.length * levels.length, actual_cards_this_run: generated.length, cards: generated }, null, 2));
